### ISSUE TITLE
ProgrammingError at /finding/open when viewing findings

### ISSUE THREAD

**Issue by tmsteen** [OWASP/django-DefectDojo#111]
When navigating to the findings tab, or trying to view findings from a test I get an error about a table that is unable to be found.  I am still able to edit a finding from the test page and view the pertinent data.    

![image](https://cloud.githubusercontent.com/assets/8290250/18357033/f7ab7624-75b4-11e6-91fb-e6c63a0a4677.png)

**Comment by devGregA** [comment]
@grendel513  you know this area better than me.

**Comment by grendel513** [comment]
@tmsteen will you please try to run `python manage.py makemigrations dojo` and `python manage.py migrate` - looks like you have the latest code but did not run the database migrations needed.  See our documentation on upgrading here http://defectdojo.readthedocs.io/en/latest/upgrading.html

Also, make sure you have all the requirements installed.  They are listed in the setup.py file: https://github.com/OWASP/django-DefectDojo/blob/master/setup.py

**Comment by tmsteen** [comment]
running those commands results in 'no changes detected' and subsequently 'no migrations to apply'.  Going through the update documentation when I try the 'bower install' step I get 'bower                     invalid-meta The "name" is recommended to be lowercase, can contain digits, dots, dashes'.

Appears all requirements are installed.

**Comment by tmsteen** [comment]
in `dojo/templates/dojo/report_filter_snippet.html` line 11, there may be an extra {{field}} tag. When I remove it I am able to move past this particular error when navigating to the reports builder page.  But still get an error when trying to view findings from a test.
![image](https://cloud.githubusercontent.com/assets/8290250/18361889/62ccdff6-75c9-11e6-875c-99ec77e67cd4.png)

**Comment by devGregA** [comment]
Hi everyone, I just reran everything after nuking my pip libraries to make sure there wasn't dependencies missing, etc like we were facing yesterday. I didn't have any issues. Is there a chance something is jumbled? I remember we had two instances e.g. tmp/ and /django-DefectDojo. I know I watched y'all do a clean install. Somehow, I'm fairly certain now you have old code. No idea how, but I can't figure out how else to explain it.

**Comment by tmsteen** [comment]
certainly possible.  is there a way to nuke the DD install but preserve the DB? Just run the full update process?

**Comment by devGregA** [comment]
Yes. One correction on my last statement: That PROTO error we saw was valid. I just pushed a fix.
For backing up:
1. create a backup file: mysqldump -uUSER -pPASSWORD DATABASE > backup.sql
2. pull a new copy: git clone https://github.com/OWASP/django-DefectDojo
3. Run ./setup.bash enter a dummy_db in the script
4. add correct db info into dojo/settings.py
5. Run python manage.py syncdb from the django-defectDojo directory
6. Run ./reports.sh
7. change the wkhtml path in dojo/settings.py from usr/local/bin to /usr/bin
8. Refer to http://defectdojo.readthedocs.io/en/latest/features.html#reports
9. run celery -A dojo worker -l info --concurrency 3

fingers crossed.

**Comment by devGregA** [comment]
Last edit @grendel513 also a bug in metrics if you try to visit product metrics. I pushed a hot fix. Everything seems to be working now. I think we should consider freezing features until we get the CI coverage up? Thoughts? I will make the tests a priority for myself.

**Comment by tmsteen** [comment]
followed those steps.  Back up and running but still getting the same error.  When I ran the syncdb command, it still said there were no migrations to apply.

**Comment by devGregA** [comment]
does the dummy db still exist? if so take the backup you made and run mysql -uroot -p dummy_db < back.sql and then point your settings at the dummy_db.

**Comment by tmsteen** [comment]
that did it. I think it is all working now.  You guys rock.  Let me know if you need documentation on anything we did to get it working.

**Comment by devGregA** [comment]
Awesome! Glad to hear it! No idea how we got into such a bad state, but I'm glad we got it resolved. :beers:
