### ISSUE TITLE
Product Type Metrics date time error

### ISSUE THREAD

**Issue by grendel513** [OWASP/django-DefectDojo#128]
@devGregA - one more.  Product type metrics breaks when selecting period with actual findings in it:

`TypeError at /metrics/product/type
can't compare datetime.datetime to datetime.date
Request Method:	GET
Request URL:	http://127.0.0.1:8000/metrics/product/type?date=4&status=
Django Version:	1.8.10
Exception Type:	TypeError
Exception Value:	
can't compare datetime.datetime to datetime.date
Exception Location:	/Users/jpaz/defect-dojo/dojo/utils.py in get_period_counts, line 366
Python Executable:	/Users/jpaz/.virtualenvs/dojo/bin/python
Python Version:	2.7.12
Python Path:	
['/Users/jpaz/defect-dojo',
 '/Users/jpaz/.virtualenvs/dojo/lib/python27.zip',
 '/Users/jpaz/.virtualenvs/dojo/lib/python2.7',
 '/Users/jpaz/.virtualenvs/dojo/lib/python2.7/plat-darwin',
 '/Users/jpaz/.virtualenvs/dojo/lib/python2.7/plat-mac',
 '/Users/jpaz/.virtualenvs/dojo/lib/python2.7/plat-mac/lib-scriptpackages',
 '/Users/jpaz/.virtualenvs/dojo/lib/python2.7/lib-tk',
 '/Users/jpaz/.virtualenvs/dojo/lib/python2.7/lib-old',
 '/Users/jpaz/.virtualenvs/dojo/lib/python2.7/lib-dynload',
 '/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7',
 '/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-darwin',
 '/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-tk',
 '/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-mac',
 '/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-mac/lib-scriptpackages',
 '/Users/jpaz/.virtualenvs/dojo/lib/python2.7/site-packages',
 '/Users/jpaz/defect-dojo']
Server time:	Wed, 5 Oct 2016 11:18:09 -0500`

I tried and saw it break with:  past 30 days, past 90 days, current year, etc.  Any period with findings in it will break.

**Comment by devGregA** [comment]
@grendel513 can you please double check? I don't get this error.

![screen shot 2016-10-05 at 2 02 46 pm](https://cloud.githubusercontent.com/assets/4741312/19127429/89675a56-8b04-11e6-96eb-c62feca2dbfb.png)

**Comment by grendel513** [comment]
Still seeing it:  
![screen shot 2016-10-05 at 2 18 08 pm](https://cloud.githubusercontent.com/assets/233694/19127956/d707a6a6-8b06-11e6-8bf0-1e8bd08b115c.png)

![screen shot 2016-10-05 at 2 19 39 pm](https://cloud.githubusercontent.com/assets/233694/19127962/df6da368-8b06-11e6-99da-7b70833374f7.png)

Both new_date and end_date are datetime.datetime objects, but I believe finding.date is not, it is a datetime.date object.

Maybe your data does not hit this logic block?

**Comment by devGregA** [comment]
looks like this was present before my pushes. I've seen this error before. I think it stems from finding.date sometimes being a date and other times being a datetime. I tried converting them back and forth and still get errors, which ultimate led to this https://github.com/OWASP/django-DefectDojo/blob/master/dojo/utils.py#L224. I will come up with something similar until I can trace down the exact cause.

**Comment by devGregA** [comment]
Have a patch waiting for travis to finish before pushing https://github.com/devGregA/django-DefectDojo/commit/cd97e83bc073f93416aa7f10631357f2b7c0e6a5

**Comment by grendel513** [comment]
This may be one of the import tools adding a date instead of a datetime
object when importing the findings.

**Comment by devGregA** [comment]
@grendel513 can you confirm this is resolved for you?

**Comment by grendel513** [comment]
@devGregA I still get the error...did you push the fix? I pulled from Master just now and only saw the CONTRIBUTING.md update

**Comment by devGregA** [comment]
yes here https://github.com/OWASP/django-DefectDojo/commit/cd97e83bc073f93416aa7f10631357f2b7c0e6a5

**Comment by grendel513** [comment]
Still saw a couple of issues...pull request
https://github.com/OWASP/django-DefectDojo/pull/133 addressed them.

Thanks!

Jay
