### ISSUE TITLE
Alerts are recalculated several times per page load

### ISSUE THREAD

**Issue by YSaxon** [OWASP/django-DefectDojo#220]
**IMPORTANT NOTE:** This is a swag reward issue.  If interested please reach out to @grendel513 to get the requirements.  Please do not start work before you have had a conversation with him.
You can reach him via OWASP Slack https://owasp.slack.com/messages/@jjpaz
 
---------------------------------------------------------------------------------------------------

I noticed in testing #217 and #219 that alerts are being recalculated at least 4 times for _every_ page load, just to construct the header bar. [Base.html](https://github.com/OWASP/django-DefectDojo/blob/master/dojo/templates/base.html#L97) calls alert_count 3 times and alert_nav_items once [(templates defined here)](https://github.com/OWASP/django-DefectDojo/blob/master/dojo/templatetags/navigation_tags.py#L10). Those call [get_alert](https://github.com/OWASP/django-DefectDojo/blob/master/dojo/utils.py#L599) which for better or worse recalculates what alerts should be displayed from scratch every time.

Something like this in [navigation_tags.py](https://github.com/OWASP/django-DefectDojo/blob/master/dojo/templatetags/navigation_tags.py) would fix it, but I feel like there ought to be a better way. At least for the 3 alert_count calls, there ought to be a way to just save it to a variable in [base.html](https://github.com/OWASP/django-DefectDojo/blob/master/dojo/templates/base.html#L97) the first time and reference that.

```
import weakref
alerts_cache = weakref.WeakKeyDictionary()
def get_alerts_from_cache(context):
    request = context['request']
    user = context['request'].user
    if request in alerts_cache:
        return alerts_cache[request]
    alerts_cache[request]=get_alerts(user)
    return alerts_cache[request]

@register.inclusion_tag('alert_nav_items.html',takes_context=True)
def alert_nav_items(context):
    alerts = get_alerts_from_cache(context)
    return {'alerts': alerts[:12]}


@register.simple_tag(takes_context=True)
def alert_count(context):
    count = len(get_alerts_from_cache(context))
    return count if count > 0 else ''
```

**Comment by grendel513** [comment]
@YSaxon - thanks for this, and I agree.  The better way is to have an alerts model and store them in the DB as they happen.  This will also allow users to silence the alerts if desired.

**Comment by devGregA** [comment]
@grendel513 I think fixing this should be a swag issue. Would you mind doing the writeup? Here is an example of what I have been doing outline the work required https://github.com/OWASP/django-DefectDojo/issues/146

**Comment by grendel513** [comment]
@devGregA - I agree, I'll get it documented today or tomorrow.

**Comment by devGregA** [comment]
Fixed by https://github.com/OWASP/django-DefectDojo/pull/318

**Comment by p3r1c0** [comment]
Hi @devGregA @grendel513,
I think that this issue is still pending. 
We are using DefectDojo and we have some performance problems. In consequence, I've been reviewing where is the problem and I have been be able to see that the application do a lot of alert/count request, even where no user is using the application (only with the interface opened) . I could prove this intercepting the requests/responses with a proxy. 
I think that could be necessary improve this section. 
In case that you think that our performance problems is not related to this, please let me know.
Best regards,
